eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9993/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: microservice-user
          uri: lb://microservice-user
          predicates:
            - Path=/utilisateur/**
          filters:
            - RewritePath=/utilisateur/(?<path>.*), /${path}

        - id: microservice-projet
          uri: lb://microservice-projet
          predicates:
            - Path=/projet/**
          filters:
            - RewritePath=/projet/(?<path>.*), /${path}
